export const CURSOR_KEYS = ['hand', 'sword', 'loot', 'target', 'arrow', 'talk'] as const;
export type CursorKey = (typeof CURSOR_KEYS)[number];

export const POPUP_TYPES = ['twitter'] as const;
export type PopupType = (typeof POPUP_TYPES)[number];

export const MUSIC_KEYS = ['village', 'beach', 'forest', 'cave', 'desert', 'lavaland', 'boss'] as const;
export type MusicKey = (typeof MUSIC_KEYS)[number];

export const AUDIO_SOUND_KEYS = [
    'loot',
    'hit1',
    'hit2',
    'hurt',
    'heal',
    'chat',
    'revive',
    'death',
    'firefox',
    'achievement',
    'kill1',
    'kill2',
    'noloot',
    'teleport',
    'chest',
    'npc',
    'npc-end',
] as const;
export type AudioSoundKey = (typeof AUDIO_SOUND_KEYS)[number];

export const SPRITE_KEYS = [
    'hand',
    'sword',
    'loot',
    'target',
    'arrow',
    'talk',
    'sparks',
    'shadow16',
    'rat',
    'skeleton',
    'skeleton2',
    'spectre',
    'boss',
    'deathknight',
    'ogre',
    'crab',
    'snake',
    'eye',
    'bat',
    'goblin',
    'wizard',
    'guard',
    'king',
    'villagegirl',
    'villager',
    'coder',
    'agent',
    'rick',
    'scientist',
    'nyan',
    'priest',
    'sorcerer',
    'octocat',
    'beachnpc',
    'forestnpc',
    'desertnpc',
    'lavanpc',
    'clotharmor',
    'leatherarmor',
    'mailarmor',
    'platearmor',
    'redarmor',
    'goldenarmor',
    'firefox',
    'death',
    'sword1',
    'axe',
    'chest',
    'sword2',
    'redsword',
    'bluesword',
    'goldensword',
    'item-sword2',
    'item-axe',
    'item-redsword',
    'item-bluesword',
    'item-goldensword',
    'item-leatherarmor',
    'item-mailarmor',
    'item-platearmor',
    'item-redarmor',
    'item-goldenarmor',
    'item-flask',
    'item-cake',
    'item-burger',
    'morningstar',
    'item-morningstar',
    'item-firepotion',
] as const;
export type SpriteKey = (typeof SPRITE_KEYS)[number];
