/* eslint-disable */
// Auto-generated from assets/content/item-loot-messages.json by tools/content/item-loot.ts.
// Do not edit this file directly.

export const ITEM_LOOT_MESSAGES = {
    "axe": "You pick up an axe",
    "bluesword": "You pick up a magic sword",
    "burger": "You can haz rat burger",
    "cake": "You eat a cake",
    "firepotion": "You feel the power of Firefox!",
    "flask": "You drink a health potion",
    "goldenarmor": "You equip a golden armor",
    "goldensword": "You pick up the ultimate sword",
    "leatherarmor": "You equip a leather armor",
    "mailarmor": "You equip a mail armor",
    "morningstar": "You pick up a morning star",
    "platearmor": "You equip a plate armor",
    "redarmor": "You equip a ruby armor",
    "redsword": "You pick up a blazing sword",
    "sword2": "You pick up a steel sword"
} as const satisfies Record<string, string>;
