import Types from '../gametypes-browser';
import type { ClientToServerProtocolAction, ServerToClientProtocolAction } from './types';

export const PLAYER_SESSION_DISPATCH_OPCODES = [
    Types.Messages.HELLO,
    Types.Messages.INTENT,
    Types.Messages.WHO,
    Types.Messages.ZONE,
    Types.Messages.CHAT,
    Types.Messages.LOOTMOVE,
    Types.Messages.AGGRO,
    Types.Messages.ATTACK,
    Types.Messages.LOOT,
    Types.Messages.OPEN,
    Types.Messages.CHECK,
    Types.Messages.ACHIEVEMENT,
    Types.Messages.CHUNK_SUBSCRIBE,
    Types.Messages.CHUNK_UNSUBSCRIBE,
] as const satisfies readonly ClientToServerProtocolAction[0][];

export const GAMECLIENT_INBOUND_HANDLER_OPCODES = [
    Types.Messages.WELCOME,
    Types.Messages.MOVE,
    Types.Messages.LOOTMOVE,
    Types.Messages.ATTACK,
    Types.Messages.SPAWN,
    Types.Messages.DESPAWN,
    Types.Messages.HEALTH,
    Types.Messages.CHAT,
    Types.Messages.EQUIP,
    Types.Messages.DROP,
    Types.Messages.TELEPORT,
    Types.Messages.DAMAGE,
    Types.Messages.POPULATION,
    Types.Messages.LIST,
    Types.Messages.DESTROY,
    Types.Messages.KILL,
    Types.Messages.HP,
    Types.Messages.BLINK,
    Types.Messages.ACHIEVEMENTS,
    Types.Messages.OUTCOME,
    Types.Messages.REJECT,
    Types.Messages.ACK,
    Types.Messages.CORRECTION,
    Types.Messages.MOVE_SYNC,
    Types.Messages.ENTITY_STATE_BATCH,
    Types.Messages.CHUNK_SNAPSHOT,
    Types.Messages.CHUNK_SNAPSHOT_PART,
    Types.Messages.CHUNK_DELTA,
] as const satisfies readonly ServerToClientProtocolAction[0][];
