import { expect, test } from 'bun:test';
import * as StartupModule from '../../../server/startup';
import * as RuntimeModule from '../../../server/runtime';

test('server startup module exports shared startup helpers', () => {
    expect(typeof StartupModule.main).toBe('function');
    expect(typeof StartupModule.getConfigFile).toBe('function');
    expect(typeof StartupModule.getWorldDistribution).toBe('function');
    expect(typeof StartupModule.createRuntimeDependencies).toBe('function');
    expect(typeof StartupModule.createServerAndMetrics).toBe('function');
    expect(typeof StartupModule.createWorlds).toBe('function');
    expect(typeof StartupModule.createPopulationChangeHandler).toBe('function');
    expect(typeof StartupModule.installWorldPopulationHooks).toBe('function');
    expect(typeof StartupModule.initializeMetricsPopulation).toBe('function');
    expect(typeof StartupModule.createServerEventEmitter).toBe('function');
    expect(typeof StartupModule.createPopulationCheckTimer).toBe('function');
    expect(typeof StartupModule.createPopulationCheckCleanup).toBe('function');
    expect(typeof StartupModule.createFatalReporter).toBe('function');
    expect(typeof StartupModule.installFatalHandlers).toBe('function');
    expect(typeof StartupModule.installShutdownHandlers).toBe('function');
    expect(typeof StartupModule.triggerFatalTestEvent).toBe('function');
    expect(typeof StartupModule.createRuntimeCleanup).toBe('function');
    expect(StartupModule.main).toBe(RuntimeModule.main);
    expect(StartupModule.getWorldDistribution).toBe(RuntimeModule.getWorldDistribution);
    expect(StartupModule.createRuntimeDependencies).toBe(RuntimeModule.createRuntimeDependencies);
    expect(StartupModule.createServerAndMetrics).toBe(RuntimeModule.createServerAndMetrics);
    expect(StartupModule.createWorlds).toBe(RuntimeModule.createWorlds);
    expect(StartupModule.createPopulationChangeHandler).toBe(RuntimeModule.createPopulationChangeHandler);
    expect(StartupModule.installWorldPopulationHooks).toBe(RuntimeModule.installWorldPopulationHooks);
    expect(StartupModule.initializeMetricsPopulation).toBe(RuntimeModule.initializeMetricsPopulation);
    expect(StartupModule.createServerEventEmitter).toBe(RuntimeModule.createServerEventEmitter);
    expect(StartupModule.createPopulationCheckTimer).toBe(RuntimeModule.createPopulationCheckTimer);
    expect(StartupModule.createPopulationCheckCleanup).toBe(RuntimeModule.createPopulationCheckCleanup);
    expect(StartupModule.createFatalReporter).toBe(RuntimeModule.createFatalReporter);
    expect(StartupModule.installFatalHandlers).toBe(RuntimeModule.installFatalHandlers);
    expect(StartupModule.installShutdownHandlers).toBe(RuntimeModule.installShutdownHandlers);
    expect(StartupModule.triggerFatalTestEvent).toBe(RuntimeModule.triggerFatalTestEvent);
    expect(StartupModule.createRuntimeCleanup).toBe(RuntimeModule.createRuntimeCleanup);
});
