import fs from 'node:fs/promises';
import path from 'node:path';
import Types from '../shared/gametypes-browser';

type MobPropertyEntry = {
    drops: Record<string, number>;
    hp: number;
    armor: number;
    weapon: number;
};

type MobPropertyMap = Record<string, MobPropertyEntry>;

const CANONICAL_PATH = new URL('../assets/content/mob-properties.json', import.meta.url);
const GENERATED_PATH = new URL('../server/generated/mob-properties.generated.ts', import.meta.url);

function fail(message: string): never {
    throw new Error(message);
}

function isInteger(value: unknown): value is number {
    return typeof value === 'number' && Number.isInteger(value);
}

function isRecord(value: unknown): value is Record<string, unknown> {
    return typeof value === 'object' && value !== null && !Array.isArray(value);
}

function getKnownMobKindNames(): string[] {
    const names: string[] = [];
    Types.forEachKind((kind, kindName) => {
        if (Types.isMob(kind)) {
            names.push(kindName);
        }
    });
    return names.sort();
}

function validateAndNormalizeMobPropertyMap(value: unknown): MobPropertyMap {
    if (!isRecord(value)) {
        fail('Canonical mob-properties content must be an object map.');
    }

    const normalized: MobPropertyMap = {};

    Object.keys(value)
        .sort()
        .forEach((mobName) => {
            const entry = value[mobName];
            if (!isRecord(entry)) {
                fail(`Mob entry "${mobName}" must be an object.`);
            }

            const mobKind = Types.getKindFromString(mobName);
            if (mobKind === undefined || !Types.isMob(mobKind)) {
                fail(`Mob entry "${mobName}" is not a known mob kind.`);
            }

            const hp = entry.hp;
            const armor = entry.armor;
            const weapon = entry.weapon;
            const drops = entry.drops;

            if (!isInteger(hp) || hp < 1) {
                fail(`Mob "${mobName}" has invalid "hp" value.`);
            }
            if (!isInteger(armor) || armor < 1) {
                fail(`Mob "${mobName}" has invalid "armor" value.`);
            }
            if (!isInteger(weapon) || weapon < 1) {
                fail(`Mob "${mobName}" has invalid "weapon" value.`);
            }
            if (!isRecord(drops)) {
                fail(`Mob "${mobName}" has invalid "drops" map.`);
            }

            const normalizedDrops: Record<string, number> = {};
            Object.keys(drops)
                .sort()
                .forEach((dropKindName) => {
                    const dropChance = drops[dropKindName];
                    if (!isInteger(dropChance) || dropChance < 0 || dropChance > 100) {
                        fail(`Mob "${mobName}" has invalid drop chance for "${dropKindName}".`);
                    }
                    const dropKind = Types.getKindFromString(dropKindName);
                    if (dropKind === undefined || !Types.isItem(dropKind)) {
                        fail(`Mob "${mobName}" references unknown/non-item drop "${dropKindName}".`);
                    }
                    normalizedDrops[dropKindName] = dropChance;
                });

            normalized[mobName] = {
                drops: normalizedDrops,
                hp,
                armor,
                weapon,
            };
        });

    const missingMobKinds = getKnownMobKindNames().filter((mobName) => !(mobName in normalized));
    if (missingMobKinds.length > 0) {
        fail(`Canonical mob-properties content is missing mob kinds: ${missingMobKinds.join(', ')}`);
    }

    return normalized;
}

async function readCanonicalData(): Promise<MobPropertyMap> {
    const payload = await fs.readFile(CANONICAL_PATH, 'utf8');
    return validateAndNormalizeMobPropertyMap(JSON.parse(payload));
}

function renderGeneratedModule(data: MobPropertyMap): string {
    const serialized = JSON.stringify(data, null, 4);
    return `/* eslint-disable */
// Auto-generated from assets/content/mob-properties.json by tools/content-mob-properties.ts.
// Do not edit this file directly.

export interface MobPropertyEntry {
    readonly drops: Record<string, number>;
    readonly hp: number;
    readonly armor: number;
    readonly weapon: number;
}

export const MOB_PROPERTIES_DATA = ${serialized} as const satisfies Record<string, MobPropertyEntry>;
`;
}

async function generate(): Promise<void> {
    const canonical = await readCanonicalData();
    const output = renderGeneratedModule(canonical);
    await fs.mkdir(path.dirname(GENERATED_PATH.pathname), { recursive: true });
    await fs.writeFile(GENERATED_PATH, output, 'utf8');
    console.log(`Generated ${GENERATED_PATH.pathname}`);
}

async function check(): Promise<void> {
    const canonical = await readCanonicalData();
    const expected = renderGeneratedModule(canonical);
    const current = await fs.readFile(GENERATED_PATH, 'utf8').catch(() => '');
    if (current !== expected) {
        fail(
            'Generated mob properties are out of date. Run `bun run content:mobs:generate` to refresh server/generated/mob-properties.generated.ts.'
        );
    }
    console.log('mob-properties generated artifact is up to date.');
}

const mode = process.argv[2] || 'generate';

if (mode === 'generate') {
    await generate();
} else if (mode === 'check') {
    await check();
} else {
    fail(`Unknown mode "${mode}". Use "generate" or "check".`);
}
