import fs from 'node:fs/promises';
import path from 'node:path';
import Types from '../shared/js/gametypes-browser';

type ItemLootMessageMap = Record<string, string>;

const CANONICAL_PATH = new URL('../assets/content/item-loot-messages.json', import.meta.url);
const GENERATED_PATH = new URL('../client/js-esm/item-loot-messages.generated.ts', import.meta.url);

function fail(message: string): never {
    throw new Error(message);
}

function isRecord(value: unknown): value is Record<string, unknown> {
    return typeof value === 'object' && value !== null && !Array.isArray(value);
}

function validateAndNormalizeItemLootMessages(value: unknown): ItemLootMessageMap {
    if (!isRecord(value)) {
        fail('Canonical item-loot-messages content must be an object map.');
    }

    const normalized: ItemLootMessageMap = {};

    Object.keys(value)
        .sort()
        .forEach((itemKindName) => {
            const message = value[itemKindName];
            if (typeof message !== 'string' || message.trim().length === 0) {
                fail(`Item "${itemKindName}" must map to a non-empty loot message string.`);
            }

            const kind = Types.getKindFromString(itemKindName);
            if (kind === undefined || !Types.isItem(kind)) {
                fail(`Item "${itemKindName}" is not a known item kind.`);
            }

            normalized[itemKindName] = message;
        });

    if (Object.keys(normalized).length === 0) {
        fail('Canonical item-loot-messages content cannot be empty.');
    }

    return normalized;
}

async function readCanonicalData(): Promise<ItemLootMessageMap> {
    const payload = await fs.readFile(CANONICAL_PATH, 'utf8');
    return validateAndNormalizeItemLootMessages(JSON.parse(payload));
}

function renderGeneratedModule(data: ItemLootMessageMap): string {
    const serialized = JSON.stringify(data, null, 4);
    return `/* eslint-disable */
// Auto-generated from assets/content/item-loot-messages.json by tools/content-item-loot-messages.ts.
// Do not edit this file directly.

export const ITEM_LOOT_MESSAGES = ${serialized} as const satisfies Record<string, string>;
`;
}

async function generate(): Promise<void> {
    const canonical = await readCanonicalData();
    const output = renderGeneratedModule(canonical);
    await fs.mkdir(path.dirname(GENERATED_PATH.pathname), { recursive: true });
    await fs.writeFile(GENERATED_PATH, output, 'utf8');
    console.log(`Generated ${GENERATED_PATH.pathname}`);
}

async function check(): Promise<void> {
    const canonical = await readCanonicalData();
    const expected = renderGeneratedModule(canonical);
    const current = await fs.readFile(GENERATED_PATH, 'utf8').catch(() => '');
    if (current !== expected) {
        fail(
            'Generated item loot messages are out of date. Run `bun run content:item-loot:generate` to refresh client/js-esm/item-loot-messages.generated.ts.'
        );
    }
    console.log('item-loot-messages generated artifact is up to date.');
}

const mode = process.argv[2] || 'generate';

if (mode === 'generate') {
    await generate();
} else if (mode === 'check') {
    await check();
} else {
    fail(`Unknown mode "${mode}". Use "generate" or "check".`);
}
