import { expect, test } from 'bun:test';
import * as MainModuleNs from '../../server/js/main';
import * as MainRuntimeModuleNs from '../../server/js/main-runtime';

const MainModule = MainModuleNs as any;
const MainRuntimeModule = MainRuntimeModuleNs as any;

test('server main module exports shared startup helpers', () => {
    expect(typeof MainModule.main).toBe('function');
    expect(typeof MainModule.getConfigFile).toBe('function');
    expect(typeof MainModule.getWorldDistribution).toBe('function');
    expect(typeof MainModule.createRuntimeDependencies).toBe('function');
    expect(typeof MainModule.createServerAndMetrics).toBe('function');
    expect(typeof MainModule.createWorlds).toBe('function');
    expect(typeof MainModule.createPopulationChangeHandler).toBe('function');
    expect(typeof MainModule.installWorldPopulationHooks).toBe('function');
    expect(typeof MainModule.initializeMetricsPopulation).toBe('function');
    expect(typeof MainModule.createServerEventEmitter).toBe('function');
    expect(typeof MainModule.createPopulationCheckTimer).toBe('function');
    expect(typeof MainModule.createPopulationCheckCleanup).toBe('function');
    expect(typeof MainModule.createFatalReporter).toBe('function');
    expect(typeof MainModule.installFatalHandlers).toBe('function');
    expect(typeof MainModule.triggerFatalTestEvent).toBe('function');
    expect(typeof MainModule.createRuntimeCleanup).toBe('function');
    expect(MainModule.main).toBe(MainRuntimeModule.main);
    expect(MainModule.getWorldDistribution).toBe(MainRuntimeModule.getWorldDistribution);
    expect(MainModule.createRuntimeDependencies).toBe(MainRuntimeModule.createRuntimeDependencies);
    expect(MainModule.createServerAndMetrics).toBe(MainRuntimeModule.createServerAndMetrics);
    expect(MainModule.createWorlds).toBe(MainRuntimeModule.createWorlds);
    expect(MainModule.createPopulationChangeHandler).toBe(MainRuntimeModule.createPopulationChangeHandler);
    expect(MainModule.installWorldPopulationHooks).toBe(MainRuntimeModule.installWorldPopulationHooks);
    expect(MainModule.initializeMetricsPopulation).toBe(MainRuntimeModule.initializeMetricsPopulation);
    expect(MainModule.createServerEventEmitter).toBe(MainRuntimeModule.createServerEventEmitter);
    expect(MainModule.createPopulationCheckTimer).toBe(MainRuntimeModule.createPopulationCheckTimer);
    expect(MainModule.createPopulationCheckCleanup).toBe(MainRuntimeModule.createPopulationCheckCleanup);
    expect(MainModule.createFatalReporter).toBe(MainRuntimeModule.createFatalReporter);
    expect(MainModule.installFatalHandlers).toBe(MainRuntimeModule.installFatalHandlers);
    expect(MainModule.triggerFatalTestEvent).toBe(MainRuntimeModule.triggerFatalTestEvent);
    expect(MainModule.createRuntimeCleanup).toBe(MainRuntimeModule.createRuntimeCleanup);
});
