// @ts-nocheck
const CLOSE_CODES = {
    NORMAL: 1000,
    UNSUPPORTED_DATA: 1003,
    INVALID_PAYLOAD: 1007,
};

export const NORMAL = CLOSE_CODES.NORMAL;
export const UNSUPPORTED_DATA = CLOSE_CODES.UNSUPPORTED_DATA;
export const INVALID_PAYLOAD = CLOSE_CODES.INVALID_PAYLOAD;
export default CLOSE_CODES;
